###Testing SignUp
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "maxfan1",
    "email": "maxfan12@gmail.com",
    "password": "Password12!"
}

###Testing Login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "max6_fan",
    "password": "F1password123!"
}

###Testing Token Authentication Generation
GET http://127.0.0.1:8000/api/test_token/
Authorization: Token 

###Testing Logout
POST http://127.0.0.1:8000/api/logout/
Authorization: Token 

###Verifying Logout
GET http://127.0.0.1:8000/api/test_token/
Authorization: Token 